# Site settings
title: Get the Gist
email: contact@getthegit.io
description: > # this means to ignore newlines until "baseurl:"
  Providing quick access to commonly used code snippets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getthegist.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  getthegist

# Build settings
markdown: kramdown
